FROM debian
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends install sqlite3 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && mkdir -p /root/db
WORKDIR /root/db/
COPY chinook.db /root/db/
