version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./app/build:/usr/share/nginx/html
    command: /bin/bash -c "nginx -g 'daemon off;'"