version: "3"
services:
  sqloj:
    image: ptyin/sqloj:latest
    ports:
      - "80:80"
    build: .
    volumes:
      - D:\SQLOJ\mongodb\data:/data/db
      - D:\SQLOJ\mongodb\config:/data/configdb
      - D:\SQLOJ\sqlite:/var/lib/sqloj